
# Configuration de l’application (base de données H2, Flyway, JWT, CORS)

server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:todo;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: false
    locations: classpath:db/migration

logging:
  level:
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate.SQL: INFO

app:
  cors:
    allowed-origins: "http://localhost:4200,https://stackblitz.com"
  jwt:
    secret: "0123456789abcdef0123456789abcdef0123456789abcdef0123456789abcdef"
    expiration: 3600000
